// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqpWdKj-9IFCX-lMksdn4rUQpt_AfbSgA',
    appId: '1:169986075332:web:f7cee56a5c008d2ee23791',
    messagingSenderId: '169986075332',
    projectId: 'movie-managment-b8620',
    authDomain: 'movie-managment-b8620.firebaseapp.com',
    storageBucket: 'movie-managment-b8620.firebasestorage.app',
    measurementId: 'G-NQMFR101EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCltrNKupFPgvU4RZPTvyn4_PMo6uhazFQ',
    appId: '1:169986075332:android:73735050e5c8804be23791',
    messagingSenderId: '169986075332',
    projectId: 'movie-managment-b8620',
    storageBucket: 'movie-managment-b8620.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxwOfZ3Xl6D0EKDQKgsu2dsyu6xUOcrSA',
    appId: '1:169986075332:ios:50fa1b54d63e7a99e23791',
    messagingSenderId: '169986075332',
    projectId: 'movie-managment-b8620',
    storageBucket: 'movie-managment-b8620.firebasestorage.app',
    iosBundleId: 'com.example.movieProjet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxwOfZ3Xl6D0EKDQKgsu2dsyu6xUOcrSA',
    appId: '1:169986075332:ios:50fa1b54d63e7a99e23791',
    messagingSenderId: '169986075332',
    projectId: 'movie-managment-b8620',
    storageBucket: 'movie-managment-b8620.firebasestorage.app',
    iosBundleId: 'com.example.movieProjet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqpWdKj-9IFCX-lMksdn4rUQpt_AfbSgA',
    appId: '1:169986075332:web:67833f0eb4d6b47be23791',
    messagingSenderId: '169986075332',
    projectId: 'movie-managment-b8620',
    authDomain: 'movie-managment-b8620.firebaseapp.com',
    storageBucket: 'movie-managment-b8620.firebasestorage.app',
    measurementId: 'G-K5EV0H4P90',
  );
}
