// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfVnw4unrKpndJf--mSTWWx9fXn2N_B30',
    appId: '1:891908407810:web:6918d45e6153d438c79d1b',
    messagingSenderId: '891908407810',
    projectId: 'movies-c699a',
    authDomain: 'movies-c699a.firebaseapp.com',
    storageBucket: 'movies-c699a.firebasestorage.app',
    measurementId: 'G-0TVJD9PGL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn0XfU_LqVm9Gaqa2n2Zbo6nWFQI00gVM',
    appId: '1:891908407810:android:6e147d597c1f1a9ac79d1b',
    messagingSenderId: '891908407810',
    projectId: 'movies-c699a',
    storageBucket: 'movies-c699a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCy3utqsM6T4g8ePjOtdM7iW-j6U9cIjY',
    appId: '1:891908407810:ios:a9ac97d1da7466d5c79d1b',
    messagingSenderId: '891908407810',
    projectId: 'movies-c699a',
    storageBucket: 'movies-c699a.firebasestorage.app',
    iosBundleId: 'com.example.movieProjet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCy3utqsM6T4g8ePjOtdM7iW-j6U9cIjY',
    appId: '1:891908407810:ios:a9ac97d1da7466d5c79d1b',
    messagingSenderId: '891908407810',
    projectId: 'movies-c699a',
    storageBucket: 'movies-c699a.firebasestorage.app',
    iosBundleId: 'com.example.movieProjet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfVnw4unrKpndJf--mSTWWx9fXn2N_B30',
    appId: '1:891908407810:web:81437ddc61771071c79d1b',
    messagingSenderId: '891908407810',
    projectId: 'movies-c699a',
    authDomain: 'movies-c699a.firebaseapp.com',
    storageBucket: 'movies-c699a.firebasestorage.app',
    measurementId: 'G-E7TKX596MP',
  );
}
